# Generated by Django 5.0.7 on 2024-07-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
