# Generated by Django 5.1 on 2024-11-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_logged_in',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_logged_ins',
            field=models.BooleanField(default=False),
        ),
    ]
