# Generated by Django 5.1 on 2024-11-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_userprofile_has_logged_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='has_logged_ins',
            new_name='has_logged_in',
        ),
    ]
