# Generated by Django 5.1.3 on 2024-11-26 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkspace', '0001_initial'),
        ('TeamworkspaceChat', '0003_alter_message_team_alter_message_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='team',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Teamworkspace.team'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamworkspace_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
